### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by xifi-kif** [cazala/coin-hive#12]
Hi, I'm trying this to test on a machine, but install fails:

```
npm install -g coin-hive
loadDep:puppeteer → get   ▐ ╢█████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/coin-hive -> /usr/local/lib/node_modules/coin-hive/bin/coin-hive

> puppeteer@0.10.2 install /usr/local/lib/node_modules/coin-hive/node_modules/puppeteer
> node install.js

/usr/local/lib/node_modules/coin-hive/node_modules/puppeteer/install.js:35
    .then(() => Promise.all(allRevisions.map(({platform, revision}) => Downloader.removeRevision(platform, revision))))
                                              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.38-std-1
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "coin-hive"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@0.10.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer


npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/build/npm/npm-debug.log
npm ERR! code 1
```

```
npm --version
3.5.2
```

```
node --version
v4.2.6
```

I googled a bit but with no luck. Since I'm new to nodejs, I can't figure out if it's my fault or some bug.

Attaching the log for debug.

[npm-debug.log.txt](https://github.com/cazala/coin-hive/files/1313900/npm-debug.log.txt)
 

Thanks

**Comment by Orgoth** [comment]
Your version of Nodejs is too old.

> node --version
> v4.2.6

You need at least version 8.0 or higher.

Under Ubuntu 16.04 is the latest version 4.2.6.
You need to install the latest version by hand.

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
