### ISSUE TITLE
Error: Address Not Available

### ISSUE THREAD

**Issue by supercyanhero** [cazala/coin-hive#13]
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 185.41.186.135:3002
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1290:19)
    at listenInCluster (net.js:1355:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1481:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:10)

What to do with that?

**Comment by soyuka** [comment]
I assume this is because you've an environment variable to `HOST`. I've made a proposal to prefix environment variables with `COIN_HIVE` #11

**Comment by supercyanhero** [comment]
No, I haven't HOST variable

**Comment by soyuka** [comment]
By default this should be `Error: listen EADDRNOTAVAIL localhost:3002`.

**Comment by supercyanhero** [comment]
I set HOST variable to 127.0.0.1 and it work
