### ISSUE TITLE
Cant install coin-hive on ubuntu 17

### ISSUE THREAD

**Issue by nodevm** [cazala/coin-hive#24]
Hello,

After installing coin-hive and try runing it

```
root@localhost:~# node coin.js
(node:10603) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/usr/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:10603) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I have the latest ubuntu 17 and also node 8.6 and npm 5.3

Edit. I removed ubuntu 17 and installed 16 and i get this: Huge log...

```
> Last login: Tue Mar  7 20:18:09 2017
> root@localhost:~# curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
> 
> ## Installing the NodeSource Node.js v8.x repo...
> 
> 
> ## Populating apt-get cache...
> 
> + apt-get update
> Hit:1 http://mirrors.linode.com/ubuntu xenial InRelease
> Get:2 http://mirrors.linode.com/ubuntu xenial-updates InRelease [102 kB]
> Get:3 http://mirrors.linode.com/ubuntu xenial-backports InRelease [102 kB]
> Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
> Get:5 http://mirrors.linode.com/ubuntu xenial-updates/main amd64 Packages [633 kB]
> Get:6 http://mirrors.linode.com/ubuntu xenial-updates/main i386 Packages [605 kB]
> Get:7 http://mirrors.linode.com/ubuntu xenial-updates/main Translation-en [266 kB]
> Get:8 http://mirrors.linode.com/ubuntu xenial-updates/restricted amd64 Packages [7,972 B]
> Get:9 http://mirrors.linode.com/ubuntu xenial-updates/restricted i386 Packages [7,988 B]
> Get:10 http://mirrors.linode.com/ubuntu xenial-updates/restricted Translation-en [2,692 B]
> Get:11 http://mirrors.linode.com/ubuntu xenial-updates/universe amd64 Packages [538 kB]
> Get:12 http://mirrors.linode.com/ubuntu xenial-updates/universe i386 Packages [513 kB]
> Get:13 http://mirrors.linode.com/ubuntu xenial-updates/universe Translation-en [218 kB]
> Get:14 http://mirrors.linode.com/ubuntu xenial-updates/multiverse amd64 Packages [15.3 kB]
> Get:15 http://mirrors.linode.com/ubuntu xenial-updates/multiverse i386 Packages [14.5 kB]
> Get:16 http://mirrors.linode.com/ubuntu xenial-updates/multiverse Translation-en [7,544 B]
> Get:17 http://mirrors.linode.com/ubuntu xenial-backports/main amd64 Packages [4,836 B]
> Get:18 http://mirrors.linode.com/ubuntu xenial-backports/main i386 Packages [4,840 B]
> Get:19 http://mirrors.linode.com/ubuntu xenial-backports/main Translation-en [3,220 B]
> Get:20 http://mirrors.linode.com/ubuntu xenial-backports/universe amd64 Packages [5,896 B]
> Get:21 http://mirrors.linode.com/ubuntu xenial-backports/universe i386 Packages [5,896 B]
> Get:22 http://mirrors.linode.com/ubuntu xenial-backports/universe Translation-en [3,060 B]
> Get:23 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [356 kB]
> Get:24 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [333 kB]
> Get:25 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [158 kB]
> Get:26 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [7,352 B]
> Get:27 http://security.ubuntu.com/ubuntu xenial-security/restricted i386 Packages [7,364 B]
> Get:28 http://security.ubuntu.com/ubuntu xenial-security/restricted Translation-en [2,432 B]
> Get:29 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [170 kB]
> Get:30 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [147 kB]
> Get:31 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [90.0 kB]
> Get:32 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [2,760 B]
> Get:33 http://security.ubuntu.com/ubuntu xenial-security/multiverse i386 Packages [2,916 B]
> Fetched 4,441 kB in 1s (3,293 kB/s)
> Reading package lists... Done
> 
> ## Confirming "xenial" is supported...
> 
> + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/xenial/Release'
> 
> ## Adding the NodeSource signing key to your keyring...
> 
> + curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
> OK
> 
> ## Creating apt sources list file for the NodeSource Node.js v8.x repo...
> 
> + echo 'deb https://deb.nodesource.com/node_8.x xenial main' > /etc/apt/sources.list.d/nodesource.list
> + echo 'deb-src https://deb.nodesource.com/node_8.x xenial main' >> /etc/apt/sources.list.d/nodesource.list
> 
> ## Running `apt-get update` for you...
> 
> + apt-get update
> Hit:1 http://mirrors.linode.com/ubuntu xenial InRelease
> Hit:2 http://mirrors.linode.com/ubuntu xenial-updates InRelease
> Hit:3 http://mirrors.linode.com/ubuntu xenial-backports InRelease
> Get:4 https://deb.nodesource.com/node_8.x xenial InRelease [4,643 B]
> Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease
> Get:6 https://deb.nodesource.com/node_8.x xenial/main Sources [761 B]
> Get:7 https://deb.nodesource.com/node_8.x xenial/main amd64 Packages [1,008 B]
> Get:8 https://deb.nodesource.com/node_8.x xenial/main i386 Packages [1,002 B]
> Fetched 7,414 B in 0s (16.3 kB/s)
> Reading package lists... Done
> 
> ## Run `apt-get install nodejs` (as root) to install Node.js v8.x and npm
> 
> root@localhost:~# sudo apt-get install -y nodejs
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following NEW packages will be installed:
>   nodejs
> 0 upgraded, 1 newly installed, 0 to remove and 103 not upgraded.
> Need to get 12.8 MB of archives.
> After this operation, 59.2 MB of additional disk space will be used.
> Get:1 https://deb.nodesource.com/node_8.x xenial/main amd64 nodejs amd64 8.6.0-1nodesource1 [12.8 MB]
> Fetched 12.8 MB in 0s (37.2 MB/s)
> Selecting previously unselected package nodejs.
> (Reading database ... 25391 files and directories currently installed.)
> Preparing to unpack .../nodejs_8.6.0-1nodesource1_amd64.deb ...
> Unpacking nodejs (8.6.0-1nodesource1) ...
> Processing triggers for man-db (2.7.5-1) ...
> Setting up nodejs (8.6.0-1nodesource1) ...
> root@localhost:~# node -v
> v8.6.0
> root@localhost:~# npm -v
> 5.3.0
> root@localhost:~# npm install -g coin-hive
> /usr/bin/coin-hive -> /usr/lib/node_modules/coin-hive/bin/coin-hive
> 
> > puppeteer@0.10.2 install /usr/lib/node_modules/coin-hive/node_modules/puppeteer
> > node install.js
> 
> fs.js:892
>   return binding.mkdir(pathModule._makeLong(path),
>                  ^
> 
> Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium'
>     at Object.fs.mkdirSync (fs.js:892:18)
>     at Object.downloadRevision (/usr/lib/node_modules/coin-hive/node_modules/puppeteer/utils/ChromiumDownloader.js:97:10)
>     at Object.<anonymous> (/usr/lib/node_modules/coin-hive/node_modules/puppeteer/install.js:33:12)
>     at Module._compile (module.js:624:30)
>     at Object.Module._extensions..js (module.js:635:10)
>     at Module.load (module.js:545:32)
>     at tryModuleLoad (module.js:508:12)
>     at Function.Module._load (module.js:500:3)
>     at Function.Module.runMain (module.js:665:10)
>     at startup (bootstrap_node.js:187:16)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! puppeteer@0.10.2 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the puppeteer@0.10.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2017-09-28T09_38_59_377Z-debug.log
> root@localhost:~# npm config set user 0
> root@localhost:~# npm config set unsafe-perm true
> root@localhost:~# npm install -g coin-hive
> /usr/bin/coin-hive -> /usr/lib/node_modules/coin-hive/bin/coin-hive
> 
> > puppeteer@0.10.2 install /usr/lib/node_modules/coin-hive/node_modules/puppeteer
> > node install.js
> 
> Downloading Chromium r497674 - 92.5 Mb [====================] 100% 0.0s
> + coin-hive@1.3.0
> added 180 packages in 8.044s
> root@localhost:~# touch coin.js
> root@localhost:~# nano coin.js
> root@localhost:~# node coin.js
> module.js:529
>     throw err;
>     ^
> 
> Error: Cannot find module 'coin-hive'
>     at Function.Module._resolveFilename (module.js:527:15)
>     at Function.Module._load (module.js:476:23)
>     at Module.require (module.js:568:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/root/coin.js:1:80)
>     at Module._compile (module.js:624:30)
>     at Object.Module._extensions..js (module.js:635:10)
>     at Module.load (module.js:545:32)
>     at tryModuleLoad (module.js:508:12)
>     at Function.Module._load (module.js:500:3)
> root@localhost:~# npm link coin-hive
> /root/node_modules/coin-hive -> /usr/lib/node_modules/coin-hive
> root@localhost:~# node coin.js
> (node:4754) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
> /usr/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory
> 
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 
> (node:4754) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
```

**Comment by nodevm** [comment]
Installed every package that was missing and managed to have it working.

**Comment by ifuyivara** [comment]
mind sharing which packages were missing? I'm getting the same error. Was it just libpangocairo-1.0.so.0 ?

**Comment by soyuka** [comment]
https://github.com/cazala/coin-hive/issues/22
