### ISSUE TITLE
Error: Evaluation failed: ReferenceError: CoinHive is not defined

### ISSUE THREAD

**Issue by luzzif** [cazala/coin-hive#27]
When I try to start the miner, I get the following error:
```
Error: Evaluation failed: ReferenceError: CoinHive is not defined
    at init (http://localhost:3002/miner.js:8:3)
    at <anonymous>:1:43
    at <anonymous>:1:78
    at Frame._rawEvaluate (/home/luzzif/WebstormProjects/monero-miner/node_modules/puppeteer/lib/FrameManager.js:250:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by cazala** [comment]
It looks like it failed to load coin-hive's client, you need to make sure you can reach coin-hive.com from wherever you are running this miner

**Comment by luzzif** [comment]
I was running the module from a VPN. I guess that's the probem. Thanks anyway!
