### ISSUE TITLE
Ubuntu 17 installation error

### ISSUE THREAD

**Issue by isbkch** [cazala/coin-hive#37]
As a software developer (not Node though) I dream of the day I run `npm install something` and it just gets installed out of the box...

Anyways, I downloaded and installed Node8 for my Ubuntu 17, removed the folder `/usr/local/lib/node_modules/coin-hive/` and run the install command again but kept getting this error:

```
npm http GET https://registry.npmjs.org/path-key

> puppeteer@0.10.2 install /usr/local/lib/node_modules/coin-hive/node_modules/puppeteer
> node install.js


/usr/local/lib/node_modules/coin-hive/node_modules/puppeteer/install.js:35
    .then(() => Promise.all(allRevisions.map(({platform, revision}) => Downloa
           ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

```
npm http 304 https://registry.npmjs.org/lru-cache
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/coin-hive/node_modules/tty-table/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules'
npm ERR! error rolling back  coin-hive@1.6.1 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/coin-hive/node_modules/tty-table/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/coin-hive/node_modules/tty-table/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules' }
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.9.33-mod-std-ipv6-64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "coin-hive"
npm ERR! cwd /home/isbkch/minegag
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/p-limit
npm http 304 https://registry.npmjs.org/builtin-modules
npm http 304 https://registry.npmjs.org/which
npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http 304 https://registry.npmjs.org/spdx-correct
npm WARN engine p-limit@1.1.0: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm ERR! Error: ENOENT, chown '/usr/local/lib/node_modules/coin-hive/node_modules/tty-table/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/is-builtin-module/node_modules/builtin-modules/static.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.9.33-mod-std-ipv6-64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "coin-hive"
npm ERR! cwd /home/isbkch/minegag
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path /usr/local/lib/node_modules/coin-hive/node_modules/tty-table/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/is-builtin-module/node_modules/builtin-modules/static.js
npm ERR! fstream_path /usr/local/lib/node_modules/coin-hive/node_modules/tty-table/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/is-builtin-module/node_modules/builtin-modules/static.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
```

Anyone has any idea how to fix this ?

**Comment by cazala** [comment]
Are you sure you are using node `v0.10.25` according to those logs, you need v8.x.x
