### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by FlareNetwork** [cazala/coin-hive#39]
root@bau:~# npm install -g coin-hive
/usr/bin/coin-hive -> /usr/lib/node_modules/coin-hive/bin/coin-hive

> puppeteer@0.10.2 install /usr/lib/node_modules/coin-hive/node_modules/puppeteer
> node install.js

fs.js:892
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium'
    at Object.fs.mkdirSync (fs.js:892:18)
    at Object.downloadRevision (/usr/lib/node_modules/coin-hive/node_modules/puppeteer/utils/ChromiumDownloader.js:97:10)
    at Object.<anonymous> (/usr/lib/node_modules/coin-hive/node_modules/puppeteer/install.js:33:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-09T18_26_21_617Z-debug.log
root@bau:~# node install.js
module.js:473
      throw err;
      ^

**Im Using Deb 8.x with Node 8.x.x & npm**

**Comment by cazala** [comment]
try `sudo npm install -g coin-hive`

**Comment by FlareNetwork** [comment]
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Oct  9 14:16:48 2017 from 185.35.216.48
root@bau:~# sudo npm install -g coin-hive
/usr/bin/coin-hive -> /usr/lib/node_modules/coin-hive/bin/coin-hive

> puppeteer@0.10.2 install /usr/lib/node_modules/coin-hive/node_modules/puppeteer
> node install.js

fs.js:892
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium'
    at Object.fs.mkdirSync (fs.js:892:18)
    at Object.downloadRevision (/usr/lib/node_modules/coin-hive/node_modules/puppeteer/utils/ChromiumDownloader.js:97:10)
    at Object.<anonymous> (/usr/lib/node_modules/coin-hive/node_modules/puppeteer/install.js:33:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-09T19_10_39_694Z-debug.log
root@bau:~# node -v
v8.6.0
root@bau:~# npm -v
5.4.2
root@bau:~#

**Comment by cazala** [comment]
this package installs `puppeteer` as a dependency, which downloads `Chromium` to your machine. It looks like you don't have permissions under the directory where it is trying to download it: `/usr/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium`

**Comment by FlareNetwork** [comment]
How i can get Perma ? chmod ?

**Comment by FlareNetwork** [comment]
*Permissions

**Comment by cazala** [comment]
tbh, i dunno :/ I thought `sudo` should've been enough..

**Comment by paOol** [comment]
try `npm cache clean`
also delete `node_modules` and `package.lock`

**Comment by FlareNetwork** [comment]
doesnt work @paOol

**Comment by kvinlambert** [comment]
Same problem here, with the same config :(

**Comment by cazala** [comment]
mmm here are some Debian required dependencies + some troubleshooting issues https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by kvinlambert** [comment]
A working solution for me: 
```sudo npm i -g coin-hive --unsafe-perm=true --allow-root```

**Comment by FlareNetwork** [comment]
Working, Thanks!


**SOLVED**
