### ISSUE TITLE
Not running in Docker

### ISSUE THREAD

**Issue by SoftCreatR** [cazala/coin-hive#57]
Hi,

I'm currently trying to make this worker inside a Docker container. It works fine on the machine itself, but when running the Docker container, all i get is

```
Initializing...
/usr/local/lib/node_modules/coin-hive/bin/coin-hive:175
process.stdin.setRawMode(true);
              ^

TypeError: process.stdin.setRawMode is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/coin-hive/bin/coin-hive:175:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by cazala** [comment]
I just fixed this and released it under version `v1.9.1`
